name: hello world

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo only ran on master