on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
name: create release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create Release
        id: create_release
        uses: rymndhng/release-on-push-action@master
        with:
          strategy: minor
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          git archive --format=zip master -o dhlparcel_shipping.zip
      - name: output upload_url
        run: echo ${{ steps.create_release.outputs.upload_url }}